databases:
  - name: smartairbnb
    plan: free

services:
  - type: web
    name: smart-airbnb
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python init_render_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartairbnb
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
